type D1Result<T = any> = { results?: T[]; success?: boolean; meta?: any };
type D1Statement = { bind: (...values: any[]) => D1Statement; first: <T = any>() => Promise<T | null>; all: <T = any>() => Promise<D1Result<T>>; run: () => Promise<any> };
type D1Database = { prepare: (sql: string) => D1Statement; batch: (statements: D1Statement[]) => Promise<any[]>; exec: (sql: string) => Promise<any> };
type R2ObjectBody = { body: ReadableStream; httpMetadata?: any; customMetadata?: Record<string,string>; writeHttpMetadata?: (headers: Headers) => void };
type R2Bucket = { get: (key: string) => Promise<R2ObjectBody | null>; put: (key: string, value: ArrayBuffer | ReadableStream | string, options?: any) => Promise<any>; delete: (key: string) => Promise<void> };

type Env = {
  DB: D1Database;
  MEDIA: R2Bucket;
  ASSETS: { fetch: (request: Request) => Promise<Response> };
  DOMAIN?: string;
  GOOGLE_CLIENT_ID?: string;
  JOOBLE_API_KEY?: string;
  JOOBLE_BASE_URL?: string;
  DOKU_CLIENT_ID?: string;
  DOKU_SECRET_KEY?: string;
  DOKU_ENV?: string;
  ADMIN_EMAIL?: string;
  TURNSTILE_SECRET_KEY?: string;
  TURNSTILE_SITE_KEY?: string;
  PUSH_GATEWAY_URL?: string;
  PUSH_GATEWAY_TOKEN?: string;
  BACKUP_PREFIX?: string;
};

type User = { id:number; username:string|null; email:string; full_name:string; address:string; wa:string; city:string; postal_code:string; provider:string; avatar_url:string; role:string; status:string; email_verified:number; created_at:string };

const STATE_KEYS = new Set(['ainfo-v9-state','ainfo-admin-articles','ainfo-admin-products','ainfo-admin-videos','ainfo-admin-jobs','ainfo-footer-pages','ainfo-push-campaigns','ainfo-shop-categories','ainfo-job-settings']);
const ADMIN_ROLES = new Set(['editor','admin','superadmin']);
const USER_ROLES = new Set(['reader','contributor','reporter','editor','admin','superadmin']);
const SESSION_SECONDS = 60 * 60 * 24 * 30;
const enc = new TextEncoder();

const json = (data:any, status=200, headers:HeadersInit={}) => new Response(JSON.stringify(data), { status, headers: { 'content-type':'application/json; charset=utf-8', 'cache-control':'no-store', ...headers } });
const text = (body:string, status=200, type='text/plain; charset=utf-8', headers:HeadersInit={}) => new Response(body, { status, headers: { 'content-type':type, ...headers } });
const domain = (env:Env) => (env.DOMAIN || 'https://www.ainfo.web.id').replace(/\/$/,'');
const nowIso = () => new Date().toISOString();
const randomToken = (bytes=32) => { const a = crypto.getRandomValues(new Uint8Array(bytes)); return base64url(a); };
const base64url = (bytes:Uint8Array) => btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const base64 = (bytes:Uint8Array) => btoa(String.fromCharCode(...bytes));
const escapeHtml = (s:any) => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c] as string));
const slugify = (s:string) => s.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,140) || 'artikel';

async function sha256(value:string){ const out = await crypto.subtle.digest('SHA-256', enc.encode(value)); return base64url(new Uint8Array(out)); }
async function hmacSha256Base64(secret:string, value:string){ const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']); const sig=await crypto.subtle.sign('HMAC',key,enc.encode(value)); return base64(new Uint8Array(sig)); }
async function passwordHash(password:string){
  const iterations=210000, salt=crypto.getRandomValues(new Uint8Array(16));
  const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);
  const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations},key,256);
  return `pbkdf2_sha256$${iterations}$${base64url(salt)}$${base64url(new Uint8Array(bits))}`;
}
function b64urlDecode(s:string){ s=s.replace(/-/g,'+').replace(/_/g,'/'); while(s.length%4)s+='='; const raw=atob(s); return Uint8Array.from(raw,c=>c.charCodeAt(0)); }
async function passwordVerify(password:string, stored:string){
  try { const [scheme,it,salt,expected]=stored.split('$'); if(scheme!=='pbkdf2_sha256') return false; const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']); const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:b64urlDecode(salt),iterations:Number(it)},key,256); return timingSafe(base64url(new Uint8Array(bits)),expected); } catch { return false; }
}
function timingSafe(a:string,b:string){ if(a.length!==b.length)return false; let v=0; for(let i=0;i<a.length;i++)v|=a.charCodeAt(i)^b.charCodeAt(i); return v===0; }
function cookies(req:Request){ const out:Record<string,string>={}; for(const part of (req.headers.get('cookie')||'').split(';')){ const i=part.indexOf('='); if(i>0)out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim()); } return out; }
function cookie(name:string,value:string,maxAge:number,httpOnly=true,secure=true){ return `${name}=${encodeURIComponent(value)}; Path=/; Max-Age=${maxAge}; SameSite=Lax${secure?'; Secure':''}${httpOnly?'; HttpOnly':''}`; }
function publicUser(u:User|null){ if(!u)return null; return { id:u.id,username:u.username,email:u.email,full_name:u.full_name,address:u.address,wa:u.wa,city:u.city,postal_code:u.postal_code,provider:u.provider,avatar_url:u.avatar_url,role:u.role,status:u.status,created_at:u.created_at,profile_complete:Boolean(u.full_name&&u.address&&u.wa&&u.email) }; }

async function currentUser(req:Request, env:Env):Promise<User|null>{
  const token=cookies(req).ainfo_session; if(!token)return null; const hash=await sha256(token); const epoch=Math.floor(Date.now()/1000);
  const row=await env.DB.prepare(`SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? LIMIT 1`).bind(hash,epoch).first<User>();
  return row || null;
}
async function createSession(req:Request, env:Env, userId:number){ const token=randomToken(40),hash=await sha256(token),exp=Math.floor(Date.now()/1000)+SESSION_SECONDS; const ua=(req.headers.get('user-agent')||'').slice(0,400),ip=await sha256(req.headers.get('cf-connecting-ip')||'local'); await env.DB.prepare('INSERT INTO sessions(token_hash,user_id,expires_at,ip_hash,user_agent) VALUES(?,?,?,?,?)').bind(hash,userId,exp,ip,ua).run(); return token; }
async function audit(req:Request,env:Env,user:User|null,action:string,entityType='',entityId='',details:any={}){ const ip=await sha256(req.headers.get('cf-connecting-ip')||'local'); await env.DB.prepare('INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,details_json,ip_hash) VALUES(?,?,?,?,?,?)').bind(user?.id||null,action,entityType,String(entityId||''),JSON.stringify(details),ip).run(); }
async function requireUser(req:Request, env:Env){ const u=await currentUser(req,env); if(!u)return {error:json({error:'unauthorized',message:'Silakan login terlebih dahulu.'},401)}; if(u.status!=='active')return {error:json({error:'account_suspended',message:'Akun sedang ditangguhkan.'},403)}; return {user:u}; }
async function requireAdmin(req:Request,env:Env,minRole='editor'){ const r=await requireUser(req,env); if(r.error)return r; const rank:Record<string,number>={reader:0,contributor:1,reporter:2,editor:3,admin:4,superadmin:5}; if((rank[r.user!.role]||0)<(rank[minRole]||3))return {error:json({error:'forbidden',message:'Akses dashboard tidak diizinkan.'},403)}; return r; }

async function ensureCsrf(req:Request){ const c=cookies(req); let token=c.ainfo_csrf; if(!token)token=randomToken(24); return token; }
async function csrfGuard(req:Request){ if(['GET','HEAD','OPTIONS'].includes(req.method))return true; const c=cookies(req).ainfo_csrf||''; const h=req.headers.get('x-csrf-token')||''; return Boolean(c&&h&&timingSafe(c,h)); }
async function rateLimit(env:Env,bucket:string,subject:string,limit:number,seconds:number){ const now=Math.floor(Date.now()/1000), exp=now+seconds; const row=await env.DB.prepare('SELECT hits,expires_at FROM rate_limits WHERE bucket=? AND subject=?').bind(bucket,subject).first<any>(); if(!row||Number(row.expires_at)<=now){ await env.DB.prepare('INSERT INTO rate_limits(bucket,subject,hits,expires_at) VALUES(?,?,1,?) ON CONFLICT(bucket,subject) DO UPDATE SET hits=1,expires_at=excluded.expires_at').bind(bucket,subject,exp).run(); return true; } if(Number(row.hits)>=limit)return false; await env.DB.prepare('UPDATE rate_limits SET hits=hits+1 WHERE bucket=? AND subject=?').bind(bucket,subject).run(); return true; }

async function readJson(req:Request,max=512*1024){ const len=Number(req.headers.get('content-length')||0); if(len>max)throw new Error('payload_too_large'); return await req.json(); }
function withSecurity(res:Response, path:string){ const h=new Headers(res.headers); h.set('x-content-type-options','nosniff'); h.set('referrer-policy','strict-origin-when-cross-origin'); h.set('permissions-policy','geolocation=(self), camera=(), microphone=()'); h.set('x-frame-options','SAMEORIGIN'); h.set('cross-origin-opener-policy','same-origin-allow-popups'); h.set('strict-transport-security','max-age=31536000; includeSubDomains; preload'); h.set('content-security-policy',"default-src 'self' https: data: blob:; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://accounts.google.com https://pagead2.googlesyndication.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; img-src 'self' https: data: blob:; media-src 'self' https: blob:; connect-src 'self' https:; frame-src https://accounts.google.com https://googleads.g.doubleclick.net https://*.google.com; font-src 'self' https://cdnjs.cloudflare.com https://cdn.jsdelivr.net data:; object-src 'none'; base-uri 'self'; frame-ancestors 'self'; form-action 'self' https://wa.me"); if(path.startsWith('/admin')){ h.set('cache-control','no-store, private'); h.set('x-robots-tag','noindex,nofollow,noarchive'); } return new Response(res.body,{status:res.status,statusText:res.statusText,headers:h}); }

async function authConfig(env:Env){ return json({google_client_id:env.GOOGLE_CLIENT_ID||'',google_enabled:Boolean(env.GOOGLE_CLIENT_ID),turnstile_enabled:Boolean(env.TURNSTILE_SECRET_KEY&&env.TURNSTILE_SITE_KEY),turnstile_site_key:env.TURNSTILE_SITE_KEY||''}); }
async function authMe(req:Request,env:Env){ return json({user:publicUser(await currentUser(req,env))}); }
async function maybeAdminByEmail(env:Env,email:string){ return Boolean(env.ADMIN_EMAIL&&env.ADMIN_EMAIL.trim().toLowerCase()===email.trim().toLowerCase()); }
async function verifyTurnstile(req:Request,env:Env,token?:string){ if(!env.TURNSTILE_SECRET_KEY||!env.TURNSTILE_SITE_KEY)return true; if(!token)return false; const fd=new FormData(); fd.set('secret',env.TURNSTILE_SECRET_KEY); fd.set('response',token); const ip=req.headers.get('cf-connecting-ip'); if(ip)fd.set('remoteip',ip); const r=await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',body:fd}); const d=await r.json(); return Boolean(d.success); }

async function register(req:Request,env:Env){
  const ip=await sha256(req.headers.get('cf-connecting-ip')||'local'); if(!await rateLimit(env,'register',ip,8,3600))return json({error:'rate_limited',message:'Terlalu banyak percobaan registrasi.'},429);
  const d=await readJson(req); const username=String(d.username||'').trim().toLowerCase(),email=String(d.email||'').trim().toLowerCase(),password=String(d.password||'');
  if(!/^[a-z0-9._-]{3,32}$/.test(username))return json({error:'invalid_username',message:'Username 3–32 karakter.'},400); if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json({error:'invalid_email',message:'Email tidak valid.'},400); if(password.length<8)return json({error:'weak_password',message:'Password minimal 8 karakter.'},400); if(!await verifyTurnstile(req,env,d.turnstileToken))return json({error:'turnstile_failed',message:'Verifikasi keamanan gagal.'},400);
  const role=await maybeAdminByEmail(env,email)?'superadmin':'reader'; const hash=await passwordHash(password);
  try{ const run=await env.DB.prepare('INSERT INTO users(username,email,password_hash,provider,role,email_verified) VALUES(?,?,?,?,?,0)').bind(username,email,hash,'local',role).run(); const id=Number(run.meta?.last_row_id||run.meta?.lastRowId); const u=await env.DB.prepare('SELECT * FROM users WHERE id=?').bind(id).first<User>(); const session=await createSession(req,env,id); await audit(req,env,u,'auth.register','user',String(id)); return json({ok:true,user:publicUser(u),needs_profile:true},201,{'set-cookie':cookie('ainfo_session',session,SESSION_SECONDS,true,new URL(req.url).protocol==='https:')}); }catch{return json({error:'account_exists',message:'Username atau email sudah terdaftar.'},409)}
}
async function login(req:Request,env:Env){ const ip=await sha256(req.headers.get('cf-connecting-ip')||'local'); if(!await rateLimit(env,'login',ip,20,900))return json({error:'rate_limited',message:'Terlalu banyak percobaan login.'},429); const d=await readJson(req); const id=String(d.identifier||'').trim().toLowerCase(),password=String(d.password||''); const u=await env.DB.prepare('SELECT * FROM users WHERE lower(email)=? OR lower(username)=? LIMIT 1').bind(id,id).first<User & {password_hash:string}>(); if(!u||!u.password_hash||!await passwordVerify(password,u.password_hash))return json({error:'invalid_credentials',message:'Email/username atau password salah.'},401); if(u.status!=='active')return json({error:'account_suspended',message:'Akun sedang ditangguhkan.'},403); const s=await createSession(req,env,u.id); await audit(req,env,u,'auth.login','user',String(u.id)); return json({ok:true,user:publicUser(u),needs_profile:!publicUser(u)?.profile_complete},200,{'set-cookie':cookie('ainfo_session',s,SESSION_SECONDS,true,new URL(req.url).protocol==='https:')}); }
async function googleLogin(req:Request,env:Env){ if(!env.GOOGLE_CLIENT_ID)return json({error:'google_not_configured'},503); const d=await readJson(req); const credential=String(d.credential||''); if(!credential)return json({error:'missing_credential'},400); const r=await fetch('https://oauth2.googleapis.com/tokeninfo?id_token='+encodeURIComponent(credential)); if(!r.ok)return json({error:'google_invalid',message:'Token Google tidak valid.'},401); const info=await r.json(); if(info.aud!==env.GOOGLE_CLIENT_ID||String(info.email_verified).toLowerCase()!=='true')return json({error:'google_invalid',message:'Audience atau email Google tidak valid.'},401); const email=String(info.email).toLowerCase(),sub=String(info.sub),name=String(info.name||''),avatar=String(info.picture||''); let u=await env.DB.prepare('SELECT * FROM users WHERE google_sub=? OR lower(email)=? LIMIT 1').bind(sub,email).first<User>(); if(u){ const role=await maybeAdminByEmail(env,email)?'superadmin':u.role; await env.DB.prepare('UPDATE users SET google_sub=?,provider=?,avatar_url=CASE WHEN avatar_url="" THEN ? ELSE avatar_url END,full_name=CASE WHEN full_name="" THEN ? ELSE full_name END,role=?,email_verified=1,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(sub,'google',avatar,name,role,u.id).run(); u=await env.DB.prepare('SELECT * FROM users WHERE id=?').bind(u.id).first<User>(); } else { let username=slugify(email.split('@')[0]).slice(0,24)||'user'; let n=1; while(await env.DB.prepare('SELECT id FROM users WHERE username=?').bind(username).first()){username=(slugify(email.split('@')[0]).slice(0,20)||'user')+(++n)} const role=await maybeAdminByEmail(env,email)?'superadmin':'reader'; const run=await env.DB.prepare('INSERT INTO users(username,email,full_name,provider,google_sub,avatar_url,role,email_verified) VALUES(?,?,?,?,?,?,?,1)').bind(username,email,name,'google',sub,avatar,role).run(); const uid=Number(run.meta?.last_row_id||run.meta?.lastRowId); u=await env.DB.prepare('SELECT * FROM users WHERE id=?').bind(uid).first<User>(); }
  const s=await createSession(req,env,u!.id); await audit(req,env,u!,'auth.google','user',String(u!.id)); return json({ok:true,user:publicUser(u!),needs_profile:!publicUser(u!)?.profile_complete},200,{'set-cookie':cookie('ainfo_session',s,SESSION_SECONDS,true,new URL(req.url).protocol==='https:')});
}
async function updateProfile(req:Request,env:Env){ const r=await requireUser(req,env); if(r.error)return r.error; const d=await readJson(req); const full=String(d.full_name||'').trim().slice(0,120),address=String(d.address||'').trim().slice(0,500),wa=String(d.wa||'').replace(/[^0-9+]/g,'').slice(0,24),email=String(d.email||r.user!.email).trim().toLowerCase().slice(0,200),city=String(d.city||'').trim().slice(0,120),postal=String(d.postal_code||'').trim().slice(0,20); if(!full||!address||!wa||!email)return json({error:'profile_incomplete',message:'Nama, alamat, WhatsApp dan email wajib diisi.'},400); try{await env.DB.prepare('UPDATE users SET full_name=?,address=?,wa=?,email=?,city=?,postal_code=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(full,address,wa,email,city,postal,r.user!.id).run(); const u=await env.DB.prepare('SELECT * FROM users WHERE id=?').bind(r.user!.id).first<User>(); return json({ok:true,user:publicUser(u)});}catch{return json({error:'email_exists',message:'Email sudah dipakai akun lain.'},409)} }
async function logout(req:Request,env:Env){ const token=cookies(req).ainfo_session;if(token)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha256(token)).run(); return json({ok:true},200,{'set-cookie':cookie('ainfo_session','',0,true,new URL(req.url).protocol==='https:')}); }

async function getBootstrap(env:Env){ const rows=await env.DB.prepare('SELECT key,value_json,version,updated_at FROM app_state').all<any>(); const state:Record<string,any>={}; let version=0; for(const r of rows.results||[]){try{state[r.key]=JSON.parse(r.value_json); version=Math.max(version,Number(r.version||0))}catch{}} return json({ok:true,state,version,empty:Object.keys(state).length===0}); }
async function saveState(req:Request,env:Env){ const r=await requireAdmin(req,env,'editor'); if(r.error)return r.error; const d=await readJson(req,2*1024*1024); const key=String(d.key||''); if(!STATE_KEYS.has(key))return json({error:'invalid_state_key'},400); const value=d.value; const payload=JSON.stringify(value); if(payload.length>1_800_000)return json({error:'state_too_large'},413); await env.DB.prepare(`INSERT INTO app_state(key,value_json,version,updated_by,updated_at) VALUES(?,?,1,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value_json=excluded.value_json,version=app_state.version+1,updated_by=excluded.updated_by,updated_at=CURRENT_TIMESTAMP`).bind(key,payload,r.user!.id).run(); if(key==='ainfo-admin-articles')await syncArticles(env,Array.isArray(value)?value:[],r.user!.id); if(key==='ainfo-admin-products')await syncProducts(env,Array.isArray(value)?value:[]); if(key==='ainfo-admin-jobs')await syncJobs(env,Array.isArray(value)?value:[]); await audit(req,env,r.user!,'state.update','app_state',key,{count:Array.isArray(value)?value.length:undefined}); return json({ok:true,key}); }
async function syncArticles(env:Env,list:any[],editorId:number){ const statements:D1Statement[]=[]; for(const a of list.slice(0,5000)){ const id=Number(a.id)||Math.floor(Math.random()*1e9); const title=String(a.title||'Untitled'); const slug=String(a.slug||slugify(title)); const content=JSON.stringify(Array.isArray(a.content)?a.content:[]); const readNum=Math.max(1,parseInt(String(a.read||'5'),10)||5); const views=Math.max(0,parseInt(String(a.views||'0').replace(/[^0-9]/g,''),10)||0); const published=a.publishedISO||a.published_at||(a.status==='published'?nowIso():null); statements.push(env.DB.prepare(`INSERT INTO articles(id,slug,title,excerpt,content_json,category,author_name,author_slug,image_url,status,headline,breaking,views,read_minutes,published_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET slug=excluded.slug,title=excluded.title,excerpt=excluded.excerpt,content_json=excluded.content_json,category=excluded.category,author_name=excluded.author_name,author_slug=excluded.author_slug,image_url=excluded.image_url,status=excluded.status,headline=excluded.headline,breaking=excluded.breaking,views=excluded.views,read_minutes=excluded.read_minutes,published_at=COALESCE(excluded.published_at,articles.published_at),updated_at=CURRENT_TIMESTAMP`).bind(id,slug,title,String(a.excerpt||''),content,String(a.cat||a.category||'Berita'),String(a.author||'Tim AINFO'),slugify(String(a.author||'Tim AINFO')),String(a.image||''),String(a.status||'draft'),a.headline?1:0,a.breaking?1:0,views,readNum,published)); }
  if(statements.length)for(let i=0;i<statements.length;i+=50)await env.DB.batch(statements.slice(i,i+50));
}
async function syncProducts(env:Env,list:any[]){ const st:D1Statement[]=[]; for(const p of list.slice(0,5000)){const id=Number(p.id)||Math.floor(Math.random()*1e9);st.push(env.DB.prepare(`INSERT INTO products(id,name,slug,category,image_url,price,compare_at_price,stock,seller_city,flash_sale,flash_end,rating,sold_count,status,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,'active',CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET name=excluded.name,slug=excluded.slug,category=excluded.category,image_url=excluded.image_url,price=excluded.price,compare_at_price=excluded.compare_at_price,stock=excluded.stock,seller_city=excluded.seller_city,flash_sale=excluded.flash_sale,flash_end=excluded.flash_end,rating=excluded.rating,sold_count=excluded.sold_count,updated_at=CURRENT_TIMESTAMP`).bind(id,String(p.name||'Produk'),slugify(String(p.name||'produk'))+'-'+id,String(p.cat||'Umum'),String(p.image||''),Number(p.price||0),Number(p.old||0),Number(p.stock||0),String(p.city||''),p.flashSale?1:0,p.flashEnds||null,Number(p.rating||0),parseInt(String(p.sold||'0').replace(/[^0-9]/g,''),10)||0));} if(st.length)for(let i=0;i<st.length;i+=50)await env.DB.batch(st.slice(i,i+50)); }
async function syncJobs(env:Env,list:any[]){ const st:D1Statement[]=[]; for(const j of list.slice(0,5000)){ const id=String(j.id||crypto.randomUUID()); st.push(env.DB.prepare(`INSERT INTO jobs(id,title,company,location,salary,employment_type,description,requirements_json,source,apply_url,status,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,'active',CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET title=excluded.title,company=excluded.company,location=excluded.location,salary=excluded.salary,employment_type=excluded.employment_type,description=excluded.description,requirements_json=excluded.requirements_json,source=excluded.source,apply_url=excluded.apply_url,updated_at=CURRENT_TIMESTAMP`).bind(id,String(j.title||''),String(j.company||''),String(j.location||''),String(j.salary||''),String(j.type||''),String(j.desc||j.description||''),JSON.stringify(j.req||[]),String(j.source||'AINFO'),String(j.link||''))); } if(st.length)for(let i=0;i<st.length;i+=50)await env.DB.batch(st.slice(i,i+50)); }

async function mediaUpload(req:Request,env:Env){ const r=await requireAdmin(req,env,'reporter'); if(r.error)return r.error; const fd=await req.formData(); const file=fd.get('file'); if(!(file instanceof File))return json({error:'missing_file'},400); if(file.size>8*1024*1024)return json({error:'file_too_large',message:'Maksimal 8 MB.'},413); const allowed=['image/jpeg','image/png','image/webp','image/avif']; if(!allowed.includes(file.type))return json({error:'invalid_media_type'},415); const ext=file.type==='image/jpeg'?'jpg':file.type.split('/')[1]; const key=`media/${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}.${ext}`; await env.MEDIA.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type,cacheControl:'public, max-age=31536000, immutable'}}); const url=`/media/${key}`; await env.DB.prepare('INSERT INTO media(r2_key,public_url,mime_type,size_bytes,alt_text,uploaded_by) VALUES(?,?,?,?,?,?)').bind(key,url,file.type,file.size,String(fd.get('alt')||''),r.user!.id).run(); await audit(req,env,r.user!,'media.upload','media',key,{size:file.size,type:file.type}); return json({ok:true,key,url}); }
async function serveMedia(path:string,env:Env){ const key=path.replace(/^\/media\//,''); const obj=await env.MEDIA.get(key); if(!obj)return text('Not found',404); const headers=new Headers(); obj.writeHttpMetadata?.(headers); headers.set('cache-control','public, max-age=31536000, immutable'); headers.set('etag',`"${await sha256(key)}"`); return new Response(obj.body,{headers}); }

async function listUsers(req:Request,env:Env){ const r=await requireAdmin(req,env,'admin'); if(r.error)return r.error; const rows=await env.DB.prepare('SELECT id,username,email,full_name,provider,avatar_url,role,status,created_at FROM users ORDER BY created_at DESC LIMIT 500').all<any>(); return json({users:rows.results||[]}); }
async function updateUser(req:Request,env:Env){ const r=await requireAdmin(req,env,'admin'); if(r.error)return r.error; const d=await readJson(req); const id=Number(d.id),role=String(d.role||'reader'),status=String(d.status||'active'); if(!USER_ROLES.has(role)||!['active','suspended'].includes(status))return json({error:'invalid_user_update'},400); await env.DB.prepare('UPDATE users SET role=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(role,status,id).run(); await audit(req,env,r.user!,'user.update','user',String(id),{role,status}); return json({ok:true,id,role,status}); }

async function search(req:Request,env:Env){ const u=new URL(req.url),q=(u.searchParams.get('q')||'').trim().slice(0,100); if(q.length<2)return json({articles:[],products:[],jobs:[]}); const like=`%${q.replace(/[%_]/g,'')}%`; const [a,p,j]=await Promise.all([env.DB.prepare("SELECT id,slug,title,excerpt,category,image_url,published_at,views FROM articles WHERE status='published' AND (title LIKE ? OR excerpt LIKE ? OR category LIKE ?) ORDER BY published_at DESC LIMIT 20").bind(like,like,like).all<any>(),env.DB.prepare("SELECT id,slug,name,category,image_url,price,rating,sold_count FROM products WHERE status='active' AND (name LIKE ? OR category LIKE ?) LIMIT 12").bind(like,like).all<any>(),env.DB.prepare("SELECT id,title,company,location,salary,employment_type,source,apply_url FROM jobs WHERE status='active' AND (title LIKE ? OR company LIKE ? OR location LIKE ?) LIMIT 12").bind(like,like,like).all<any>()]); return json({articles:a.results||[],products:p.results||[],jobs:j.results||[]}); }

async function commentsGet(req:Request,env:Env){ const u=new URL(req.url),articleId=Number(u.searchParams.get('article_id')||0); if(!articleId)return json({comments:[]}); const rows=await env.DB.prepare(`SELECT c.*,u.username,u.full_name,u.avatar_url FROM comments c JOIN users u ON u.id=c.user_id WHERE c.article_id=? AND c.status='published' ORDER BY c.is_pinned DESC,c.created_at ASC LIMIT 500`).bind(articleId).all<any>(); return json({comments:rows.results||[]}); }
async function commentsPost(req:Request,env:Env){ const r=await requireUser(req,env); if(r.error)return r.error; const ip=await sha256(req.headers.get('cf-connecting-ip')||'local'); if(!await rateLimit(env,'comment',`${r.user!.id}:${ip}`,20,3600))return json({error:'rate_limited'},429); const d=await readJson(req); const articleId=Number(d.article_id),parent=d.parent_id?Number(d.parent_id):null,body=String(d.body||'').trim().slice(0,3000); if(!articleId||body.length<2)return json({error:'invalid_comment'},400); const run=await env.DB.prepare('INSERT INTO comments(article_id,user_id,parent_id,body,status) VALUES(?,?,?,?,?)').bind(articleId,r.user!.id,parent,body,'published').run(); return json({ok:true,id:Number(run.meta?.last_row_id||run.meta?.lastRowId)},201); }
async function reactionPost(req:Request,env:Env){ const r=await requireUser(req,env); if(r.error)return r.error; const d=await readJson(req); const type=String(d.target_type||''),target=String(d.target_id||''),reaction=String(d.reaction||'like'); if(!['article','comment','video'].includes(type)||!target||!['like','love','haha','wow','sad','angry'].includes(reaction))return json({error:'invalid_reaction'},400); await env.DB.prepare(`INSERT INTO reactions(user_id,target_type,target_id,reaction) VALUES(?,?,?,?) ON CONFLICT(user_id,target_type,target_id) DO UPDATE SET reaction=excluded.reaction,updated_at=CURRENT_TIMESTAMP`).bind(r.user!.id,type,target,reaction).run(); const rows=await env.DB.prepare('SELECT reaction,COUNT(*) count FROM reactions WHERE target_type=? AND target_id=? GROUP BY reaction').bind(type,target).all<any>(); return json({ok:true,counts:rows.results||[]}); }
async function ratingPost(req:Request,env:Env){ const r=await requireUser(req,env); if(r.error)return r.error; const d=await readJson(req); const article=Number(d.article_id),rating=Number(d.rating); if(!article||rating<1||rating>5)return json({error:'invalid_rating'},400); await env.DB.prepare(`INSERT INTO ratings(user_id,article_id,rating) VALUES(?,?,?) ON CONFLICT(user_id,article_id) DO UPDATE SET rating=excluded.rating,updated_at=CURRENT_TIMESTAMP`).bind(r.user!.id,article,rating).run(); const agg=await env.DB.prepare('SELECT AVG(rating) avg,COUNT(*) count FROM ratings WHERE article_id=?').bind(article).first<any>(); await env.DB.prepare('UPDATE articles SET rating=?,rating_count=? WHERE id=?').bind(Number(agg?.avg||0),Number(agg?.count||0),article).run(); return json({ok:true,rating:Number(agg?.avg||0),count:Number(agg?.count||0)}); }
async function bookmarkPost(req:Request,env:Env){ const r=await requireUser(req,env); if(r.error)return r.error; const d=await readJson(req); const type=String(d.target_type||'article'),target=String(d.target_id||''),collection=String(d.collection||'Baca Nanti').slice(0,80); if(!['article','video','job','product'].includes(type)||!target)return json({error:'invalid_bookmark'},400); if(d.remove){await env.DB.prepare('DELETE FROM bookmarks WHERE user_id=? AND target_type=? AND target_id=?').bind(r.user!.id,type,target).run();return json({ok:true,bookmarked:false})} await env.DB.prepare('INSERT INTO bookmarks(user_id,target_type,target_id,collection_name) VALUES(?,?,?,?) ON CONFLICT(user_id,target_type,target_id) DO UPDATE SET collection_name=excluded.collection_name').bind(r.user!.id,type,target,collection).run(); return json({ok:true,bookmarked:true}); }

async function dokuDigest(body:string){ const hash=await crypto.subtle.digest('SHA-256',enc.encode(body)); return base64(new Uint8Array(hash)); }
async function dokuHeaders(env:Env,target:string,body:string){ const requestId=crypto.randomUUID(),timestamp=new Date().toISOString().replace(/\.\d{3}Z$/,'Z'),digest=await dokuDigest(body); const component=[`Client-Id:${env.DOKU_CLIENT_ID}`,`Request-Id:${requestId}`,`Request-Timestamp:${timestamp}`,`Request-Target:${target}`,`Digest:${digest}`].join('\n'); const signature='HMACSHA256='+await hmacSha256Base64(env.DOKU_SECRET_KEY||'',component); return {'Client-Id':env.DOKU_CLIENT_ID||'','Request-Id':requestId,'Request-Timestamp':timestamp,'Signature':signature,'Content-Type':'application/json','Accept':'application/json'}; }
async function dokuCreate(env:Env,bodyObj:any){ if(!env.DOKU_CLIENT_ID||!env.DOKU_SECRET_KEY)throw new Error('doku_not_configured'); const target='/checkout/v1/payment',body=JSON.stringify(bodyObj),base=(env.DOKU_ENV||'sandbox').toLowerCase()==='production'?'https://api.doku.com':'https://api-sandbox.doku.com'; const r=await fetch(base+target,{method:'POST',headers:await dokuHeaders(env,target,body),body}); const data=await r.json().catch(()=>({})); if(!r.ok)throw new Error(`DOKU HTTP ${r.status}: ${JSON.stringify(data).slice(0,500)}`); const paymentUrl=data?.response?.payment?.url||data?.payment?.url||''; return {raw:data,paymentUrl}; }
async function giftCheckout(req:Request,env:Env){ const r=await requireUser(req,env); if(r.error)return r.error; const d=await readJson(req); const author=String(d.author||'Penulis AINFO').slice(0,160),amount=Math.max(5000,Math.min(5000000,Number(d.amount||0))),message=String(d.message||'').slice(0,300),invoice=`AINFO-GIFT-${Date.now()}-${randomToken(4).toUpperCase()}`; const pu=publicUser(r.user!)!; const body={order:{amount,invoice_number:invoice,line_items:[{name:`Gift Author - ${author}`.slice(0,255),price:amount,quantity:1,sku:'GIFT-AUTHOR',category:'Gift Author'}]},payment:{payment_due_date:60},customer:{name:pu.full_name||pu.username||'AINFO User',email:pu.email,phone:pu.wa||''}}; try{const pay=await dokuCreate(env,body);await env.DB.prepare('INSERT INTO gifts(invoice,user_id,author_name,author_slug,amount,message,status,payment_url) VALUES(?,?,?,?,?,?,?,?)').bind(invoice,r.user!.id,author,slugify(author),amount,message,'pending',pay.paymentUrl).run();await audit(req,env,r.user!,'gift.checkout','gift',invoice,{amount,author});return json({ok:true,invoice_number:invoice,payment_url:pay.paymentUrl,method:'DOKU Checkout / e-Wallet'})}catch(e:any){return json({error:String(e.message||e).includes('doku_not_configured')?'doku_not_configured':'doku_unavailable',message:String(e.message||e)},503)} }
async function giftsList(req:Request,env:Env){ const r=await requireUser(req,env); if(r.error)return r.error; const rows=await env.DB.prepare('SELECT invoice,author_name author,amount,message,status,payment_url,created_at FROM gifts WHERE user_id=? ORDER BY created_at DESC LIMIT 100').bind(r.user!.id).all<any>(); return json({gifts:rows.results||[]}); }
async function shopCheckout(req:Request,env:Env){ const user=await currentUser(req,env); const d=await readJson(req); const customer=d.customer||{},items=Array.isArray(d.items)?d.items.slice(0,50):[],shipping=Math.max(0,Number(d.shipping||0)); if(!items.length||!customer.name||!customer.email||!customer.phone)return json({error:'invalid_checkout',message:'Data pembeli atau keranjang belum lengkap.'},400); let amount=shipping; const lines:any[]=[]; for(const item of items){const price=Math.max(0,Number(item.price||0)),qty=Math.max(1,Math.min(99,Number(item.quantity||1)));amount+=price*qty;lines.push({name:String(item.name||'Produk AINFO').slice(0,255),price,quantity:qty,sku:String(item.id||'').slice(0,64),category:'AINFO Shopping',image_url:String(item.image||'').slice(0,500)});} if(shipping)lines.push({name:'Ongkos Kirim',price:shipping,quantity:1,sku:'SHIPPING',category:'Shipping'}); const invoice=`AINFO-${Date.now()}-${randomToken(4).toUpperCase()}`; const body={order:{amount,invoice_number:invoice,line_items:lines},payment:{payment_due_date:60},customer:{name:String(customer.name).slice(0,255),email:String(customer.email).slice(0,255),phone:String(customer.phone).slice(0,32)},shipping_address:{first_name:String(customer.name).slice(0,100),address:String(customer.address||'').slice(0,400),city:String(customer.city||'').slice(0,100),postal_code:String(customer.postal_code||'').slice(0,20),phone:String(customer.phone).slice(0,32),country_code:'IDN'}}; try{const pay=await dokuCreate(env,body);await env.DB.prepare('INSERT INTO orders(invoice,user_id,status,subtotal,shipping,total,customer_json,items_json,payment_provider,payment_url) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(invoice,user?.id||null,'pending',amount-shipping,shipping,amount,JSON.stringify(customer),JSON.stringify(items),'DOKU',pay.paymentUrl).run();return json({ok:true,invoice_number:invoice,payment_url:pay.paymentUrl})}catch(e:any){return json({error:String(e.message||e).includes('doku_not_configured')?'doku_not_configured':'doku_unavailable',message:String(e.message||e)},503)} }
async function dokuWebhook(req:Request,env:Env){ if(!env.DOKU_CLIENT_ID||!env.DOKU_SECRET_KEY)return json({error:'doku_not_configured'},503); const body=await req.text(),target=new URL(req.url).pathname,client=req.headers.get('Client-Id')||'',requestId=req.headers.get('Request-Id')||'',timestamp=req.headers.get('Request-Timestamp')||'',sig=req.headers.get('Signature')||''; if(client!==env.DOKU_CLIENT_ID||!requestId||!timestamp||!sig)return json({error:'invalid_webhook_headers'},401); const digest=await dokuDigest(body),component=[`Client-Id:${client}`,`Request-Id:${requestId}`,`Request-Timestamp:${timestamp}`,`Request-Target:${target}`,`Digest:${digest}`].join('\n'),expected='HMACSHA256='+await hmacSha256Base64(env.DOKU_SECRET_KEY,component); if(!timingSafe(sig,expected))return json({error:'invalid_signature'},401); let payload:any={};try{payload=JSON.parse(body)}catch{return json({error:'invalid_json'},400)} const invoice=String(payload?.order?.invoice_number||payload?.invoice_number||''),rawStatus=String(payload?.transaction?.status||payload?.status||payload?.payment?.status||'').toUpperCase(),status=['SUCCESS','PAID','COMPLETED'].includes(rawStatus)?'paid':['EXPIRED'].includes(rawStatus)?'expired':['FAILED','DENIED','CANCELLED'].includes(rawStatus)?'failed':'pending'; try{await env.DB.prepare('INSERT INTO doku_webhook_events(request_id,invoice,payload_json,processed) VALUES(?,?,?,0)').bind(requestId,invoice,body).run()}catch{return json({ok:true,duplicate:true})} if(invoice){await env.DB.prepare('UPDATE gifts SET status=?,paid_at=CASE WHEN ?="paid" THEN CURRENT_TIMESTAMP ELSE paid_at END,updated_at=CURRENT_TIMESTAMP WHERE invoice=?').bind(status,status,invoice).run();await env.DB.prepare('UPDATE orders SET status=?,paid_at=CASE WHEN ?="paid" THEN CURRENT_TIMESTAMP ELSE paid_at END,updated_at=CURRENT_TIMESTAMP WHERE invoice=?').bind(status,status,invoice).run();} await env.DB.prepare('UPDATE doku_webhook_events SET processed=1 WHERE request_id=?').bind(requestId).run();return json({ok:true}); }

async function jooble(req:Request,env:Env){ if(!env.JOOBLE_API_KEY)return json({error:'missing_api_key',message:'JOOBLE_API_KEY belum dikonfigurasi.'},503); const u=new URL(req.url),keywords=(u.searchParams.get('keywords')||'HSE').slice(0,120),location=(u.searchParams.get('location')||'Indonesia').slice(0,120),page=Math.max(1,Number(u.searchParams.get('page')||1)); const target=(env.JOOBLE_BASE_URL||'https://id.jooble.org').replace(/\/$/,'')+`/api/${env.JOOBLE_API_KEY}`; const r=await fetch(target,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({keywords,location,page})}); const d=await r.json().catch(()=>({})); if(!r.ok)return json({error:'jooble_error',status:r.status,detail:d},502); return json(d,200,{'cache-control':'public, max-age=300'}); }
async function prayerProxy(req:Request){ const u=new URL(req.url); const search=u.pathname.endsWith('/search'); const base='https://api.myquran.com/v3'; const target=search?`${base}/sholat/kota/cari/${encodeURIComponent(u.searchParams.get('q')||'Jakarta')}`:`${base}/sholat/jadwal/${encodeURIComponent(u.searchParams.get('id')||'1301')}/${encodeURIComponent(u.searchParams.get('period')||new Date().toISOString().slice(0,7))}`; const r=await fetch(target,{headers:{accept:'application/json'}}); return new Response(r.body,{status:r.status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=1800'}}); }

async function notificationList(req:Request,env:Env){ const r=await requireAdmin(req,env,'editor');if(r.error)return r.error;const rows=await env.DB.prepare('SELECT * FROM push_campaigns ORDER BY created_at DESC LIMIT 100').all<any>();return json({notifications:rows.results||[]}); }
async function notificationCreate(req:Request,env:Env){ const r=await requireAdmin(req,env,'editor');if(r.error)return r.error;const d=await readJson(req);const title=String(d.title||'').slice(0,120),body=String(d.body||'').slice(0,500),url=String(d.url||'/').slice(0,500),topic=String(d.topic||'all').slice(0,60);if(!title||!body)return json({error:'invalid_notification'},400);const run=await env.DB.prepare('INSERT INTO push_campaigns(title,body,target_url,topic,created_by) VALUES(?,?,?,?,?)').bind(title,body,url,topic,r.user!.id).run();const id=Number(run.meta?.last_row_id||run.meta?.lastRowId);let delivery='queued';if(env.PUSH_GATEWAY_URL){delivery='gateway';await deliverPush(env,id,title,body,url,topic)}await audit(req,env,r.user!,'push.create','push_campaign',String(id),{topic});return json({ok:true,id,delivery},201); }
async function pushSubscribe(req:Request,env:Env){ const u=await currentUser(req,env);const d=await readJson(req);if(!d?.endpoint)return json({error:'invalid_subscription'},400);await env.DB.prepare(`INSERT INTO push_subscriptions(user_id,endpoint,subscription_json,topics_json,active) VALUES(?,?,?,?,1) ON CONFLICT(endpoint) DO UPDATE SET user_id=excluded.user_id,subscription_json=excluded.subscription_json,topics_json=excluded.topics_json,active=1,updated_at=CURRENT_TIMESTAMP`).bind(u?.id||null,String(d.endpoint),JSON.stringify(d),JSON.stringify(d.topics||['breaking'])).run();return json({ok:true}); }
async function deliverPush(env:Env,id:number,title:string,body:string,url:string,topic:string){ if(!env.PUSH_GATEWAY_URL)return;const rows=await env.DB.prepare('SELECT endpoint,subscription_json,topics_json FROM push_subscriptions WHERE active=1 LIMIT 5000').all<any>();let ok=0,fail=0;for(const row of rows.results||[]){let topics:any[]=[];try{topics=JSON.parse(row.topics_json)}catch{}if(topic!=='all'&&!topics.includes(topic))continue;try{const r=await fetch(env.PUSH_GATEWAY_URL,{method:'POST',headers:{'content-type':'application/json',...(env.PUSH_GATEWAY_TOKEN?{'authorization':`Bearer ${env.PUSH_GATEWAY_TOKEN}`}:{})},body:JSON.stringify({subscription:JSON.parse(row.subscription_json),notification:{title,body,url}})});if(r.ok)ok++;else fail++;}catch{fail++}}await env.DB.prepare("UPDATE push_campaigns SET status=?,sent_count=?,failed_count=?,sent_at=CURRENT_TIMESTAMP WHERE id=?").bind(fail&&ok===0?'failed':'sent',ok,fail,id).run(); }

async function health(env:Env){ const t=Date.now();let dbOk=false,r2Ok=false;try{await env.DB.prepare('SELECT 1 ok').first();dbOk=true}catch{}try{await env.MEDIA.get('__healthcheck__');r2Ok=true}catch{}return json({ok:dbOk,version:'14.0.0',mode:'production-ready',latency_ms:Date.now()-t,services:{d1:dbOk,r2:r2Ok,jooble:Boolean(env.JOOBLE_API_KEY),doku:Boolean(env.DOKU_CLIENT_ID&&env.DOKU_SECRET_KEY),google:Boolean(env.GOOGLE_CLIENT_ID),turnstile:Boolean(env.TURNSTILE_SECRET_KEY),push_gateway:Boolean(env.PUSH_GATEWAY_URL)}}); }

async function adminMetrics(req:Request,env:Env){ const r=await requireAdmin(req,env,'editor');if(r.error)return r.error; const q=async(sql:string)=>Number((await env.DB.prepare(sql).first<any>())?.n||0); const [users,articles,comments,orders,pendingOrders,gifts,paidGift,reported]=await Promise.all([q('SELECT COUNT(*) n FROM users'),q("SELECT COUNT(*) n FROM articles WHERE status='published'"),q("SELECT COUNT(*) n FROM comments WHERE status='published'"),q('SELECT COUNT(*) n FROM orders'),q("SELECT COUNT(*) n FROM orders WHERE status='pending'"),q('SELECT COUNT(*) n FROM gifts'),q("SELECT COALESCE(SUM(amount),0) n FROM gifts WHERE status='paid'"),q("SELECT COUNT(*) n FROM comment_reports WHERE status='open'")]); const revenue=Number((await env.DB.prepare("SELECT COALESCE(SUM(total),0) n FROM orders WHERE status IN ('paid','processing','shipped','completed')").first<any>())?.n||0); return json({users,articles,comments,orders,pending_orders:pendingOrders,gifts,gift_revenue:paidGift,shop_revenue:revenue,reported_comments:reported}); }
async function adminOrders(req:Request,env:Env){const r=await requireAdmin(req,env,'admin');if(r.error)return r.error;const rows=await env.DB.prepare('SELECT id,invoice,user_id,status,subtotal,shipping,total,customer_json,items_json,payment_provider,payment_url,paid_at,created_at FROM orders ORDER BY created_at DESC LIMIT 200').all<any>();return json({orders:rows.results||[]});}
async function adminGifts(req:Request,env:Env){const r=await requireAdmin(req,env,'admin');if(r.error)return r.error;const rows=await env.DB.prepare('SELECT id,invoice,user_id,author_name,amount,message,status,payment_url,paid_at,created_at FROM gifts ORDER BY created_at DESC LIMIT 200').all<any>();return json({gifts:rows.results||[]});}
async function adminAudit(req:Request,env:Env){const r=await requireAdmin(req,env,'admin');if(r.error)return r.error;const rows=await env.DB.prepare('SELECT a.*,u.email actor_email FROM audit_logs a LEFT JOIN users u ON u.id=a.actor_user_id ORDER BY a.created_at DESC LIMIT 200').all<any>();return json({audit:rows.results||[]});}

async function adminExport(req:Request,env:Env){ const r=await requireAdmin(req,env,'admin');if(r.error)return r.error;const [state,articles,products,jobs,pages]=await Promise.all([env.DB.prepare('SELECT key,value_json,version,updated_at FROM app_state').all<any>(),env.DB.prepare('SELECT * FROM articles').all<any>(),env.DB.prepare('SELECT * FROM products').all<any>(),env.DB.prepare('SELECT * FROM jobs').all<any>(),env.DB.prepare('SELECT * FROM pages').all<any>()]);await audit(req,env,r.user!,'backup.export','system','manual');return json({exported_at:nowIso(),state:state.results||[],articles:articles.results||[],products:products.results||[],jobs:jobs.results||[],pages:pages.results||[]}); }

async function articleSsr(slug:string,env:Env){ const a=await env.DB.prepare("SELECT * FROM articles WHERE slug=? AND status='published' LIMIT 1").bind(slug).first<any>(); if(!a)return text('Artikel tidak ditemukan',404);let paragraphs:string[]=[];try{paragraphs=JSON.parse(a.content_json||'[]')}catch{}const d=domain(env),url=`${d}/read/${encodeURIComponent(a.slug)}/`,img=a.image_url||`${d}/AINFO.png`,desc=a.seo_description||a.excerpt||a.title,title=a.seo_title||`${a.title} - AINFO`,jsonLd={"@context":"https://schema.org","@type":"NewsArticle",headline:a.title,image:[img],datePublished:a.published_at,dateModified:a.updated_at,author:{"@type":"Person",name:a.author_name,url:`${d}/author/${a.author_slug}/`},publisher:{"@type":"NewsMediaOrganization",name:'AINFO',url:d,logo:{"@type":"ImageObject",url:`${d}/icon-512.png`}},mainEntityOfPage:url,articleSection:a.category};const html=`<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title><meta name="description" content="${escapeHtml(desc)}"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1"><link rel="canonical" href="${escapeHtml(url)}"><meta property="og:type" content="article"><meta property="og:title" content="${escapeHtml(title)}"><meta property="og:description" content="${escapeHtml(desc)}"><meta property="og:image" content="${escapeHtml(img)}"><meta property="og:url" content="${escapeHtml(url)}"><script type="application/ld+json">${JSON.stringify(jsonLd).replace(/</g,'\\u003c')}</script><style>body{font-family:system-ui,-apple-system,sans-serif;margin:0;color:#0b1f3a;background:#fff}header,main,footer{max-width:820px;margin:auto;padding:18px}.logo{width:100px}h1{font-size:clamp(30px,6vw,52px);line-height:1.08}.meta{color:#64748b}.hero{width:100%;border-radius:18px;max-height:520px;object-fit:cover}article{font-size:19px;line-height:1.75}a{color:#1267d6}</style></head><body><header><a href="/"><img class="logo" src="/AINFO.png" alt="AINFO"></a></header><main><div class="meta">${escapeHtml(a.category)} · ${escapeHtml(a.author_name)} · ${escapeHtml(a.published_at||'')}</div><h1>${escapeHtml(a.title)}</h1><p class="meta">${escapeHtml(a.excerpt)}</p>${img?`<img class="hero" src="${escapeHtml(img)}" alt="${escapeHtml(a.title)}">`:''}<article>${paragraphs.map(p=>`<p>${escapeHtml(p)}</p>`).join('')}</article><p><a href="/#/article/${a.id}">Buka versi interaktif AINFO →</a></p></main><footer>© AINFO · Berita yang Lebih Bermakna</footer></body></html>`;return text(html,200,'text/html; charset=utf-8',{'cache-control':'public, max-age=60, s-maxage=300'}); }
async function sitemap(env:Env,news=false){ const d=domain(env),rows=await env.DB.prepare("SELECT slug,published_at,updated_at,title,image_url FROM articles WHERE status='published' AND published_at IS NOT NULL ORDER BY published_at DESC LIMIT 1000").all<any>();if(news){const recent=(rows.results||[]).filter(a=>Date.now()-new Date(a.published_at).getTime()<3*24*3600*1000).slice(0,1000);return text(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9">${recent.map(a=>`<url><loc>${escapeHtml(`${d}/read/${a.slug}/`)}</loc><news:news><news:publication><news:name>AINFO</news:name><news:language>id</news:language></news:publication><news:publication_date>${escapeHtml(a.published_at)}</news:publication_date><news:title>${escapeHtml(a.title)}</news:title></news:news></url>`).join('')}</urlset>`,200,'application/xml; charset=utf-8');}return text(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${d}/</loc><changefreq>hourly</changefreq><priority>1.0</priority></url>${(rows.results||[]).map(a=>`<url><loc>${escapeHtml(`${d}/read/${a.slug}/`)}</loc><lastmod>${escapeHtml(a.updated_at||a.published_at)}</lastmod><changefreq>daily</changefreq><priority>0.8</priority></url>`).join('')}</urlset>`,200,'application/xml; charset=utf-8'); }
async function rss(env:Env){const d=domain(env),rows=await env.DB.prepare("SELECT slug,title,excerpt,published_at FROM articles WHERE status='published' ORDER BY published_at DESC LIMIT 50").all<any>();return text(`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>AINFO</title><link>${d}</link><description>Berita yang Lebih Bermakna</description><language>id-ID</language>${(rows.results||[]).map(a=>`<item><title>${escapeHtml(a.title)}</title><link>${escapeHtml(`${d}/read/${a.slug}/`)}</link><guid>${escapeHtml(`${d}/read/${a.slug}/`)}</guid><description>${escapeHtml(a.excerpt)}</description><pubDate>${new Date(a.published_at).toUTCString()}</pubDate></item>`).join('')}</channel></rss>`,200,'application/rss+xml; charset=utf-8');}

async function route(req:Request,env:Env):Promise<Response>{ const url=new URL(req.url),p=url.pathname;
  if(p==='/api/auth/csrf'){const t=await ensureCsrf(req);return json({csrf:t},200,{'set-cookie':cookie('ainfo_csrf',t,SESSION_SECONDS,false,new URL(req.url).protocol==='https:')});}
  if(p.startsWith('/api/')&&req.method!=='GET'&&p!=='/api/doku/webhook'&&!await csrfGuard(req))return json({error:'csrf_failed',message:'Token keamanan tidak valid. Muat ulang halaman.'},403);
  if(p==='/api/health')return health(env);
  if(p==='/api/public/bootstrap')return getBootstrap(env);
  if(p==='/api/auth/config')return authConfig(env); if(p==='/api/auth/me')return authMe(req,env); if(p==='/api/auth/register'&&req.method==='POST')return register(req,env); if(p==='/api/auth/login'&&req.method==='POST')return login(req,env); if(p==='/api/auth/google'&&req.method==='POST')return googleLogin(req,env); if(p==='/api/auth/profile'&&req.method==='POST')return updateProfile(req,env); if(p==='/api/auth/logout'&&req.method==='POST')return logout(req,env);
  if(p==='/api/search')return search(req,env); if(p==='/api/comments'&&req.method==='GET')return commentsGet(req,env); if(p==='/api/comments'&&req.method==='POST')return commentsPost(req,env); if(p==='/api/reactions'&&req.method==='POST')return reactionPost(req,env); if(p==='/api/ratings'&&req.method==='POST')return ratingPost(req,env); if(p==='/api/bookmarks'&&req.method==='POST')return bookmarkPost(req,env);
  if(p==='/api/gift/checkout'&&req.method==='POST')return giftCheckout(req,env); if(p==='/api/gifts'&&req.method==='GET')return giftsList(req,env); if(p==='/api/doku/checkout'&&req.method==='POST')return shopCheckout(req,env); if(p==='/api/doku/webhook'&&req.method==='POST')return dokuWebhook(req,env);
  if(p==='/api/jobs')return jooble(req,env); if(p==='/api/prayer/search')return prayerProxy(req); if(p==='/api/prayer/month')return prayerProxy(req);
  if(p==='/api/push/subscribe'&&req.method==='POST')return pushSubscribe(req,env);
  if(p==='/api/admin/state'&&req.method==='POST')return saveState(req,env); if(p==='/api/admin/media'&&req.method==='POST')return mediaUpload(req,env); if(p==='/api/admin/metrics'&&req.method==='GET')return adminMetrics(req,env); if(p==='/api/admin/orders'&&req.method==='GET')return adminOrders(req,env); if(p==='/api/admin/gifts'&&req.method==='GET')return adminGifts(req,env); if(p==='/api/admin/audit'&&req.method==='GET')return adminAudit(req,env); if(p==='/api/admin/users'&&req.method==='GET')return listUsers(req,env); if(p==='/api/admin/users/update'&&req.method==='POST')return updateUser(req,env); if(p==='/api/admin/notifications'&&req.method==='GET')return notificationList(req,env); if(p==='/api/admin/notifications'&&req.method==='POST')return notificationCreate(req,env); if(p==='/api/admin/jooble/config'&&req.method==='POST')return json({error:'server_secret_required',message:'Pada production, JOOBLE_API_KEY harus diatur melalui Cloudflare Secret, bukan browser.'},409); if(p==='/api/admin/export'&&req.method==='GET')return adminExport(req,env);
  if(p.startsWith('/media/'))return serveMedia(p,env); if(p==='/sitemap.xml')return sitemap(env,false); if(p==='/news-sitemap.xml')return sitemap(env,true); if(p==='/rss.xml'||p==='/feed.xml')return rss(env); if(/^\/read\/[^/]+\/?$/.test(p))return articleSsr(decodeURIComponent(p.split('/')[2]),env);
  if(p==='/admin'||p==='/admin/'){const r=await requireAdmin(req,env,'editor');if(r.error)return Response.redirect(`${url.origin}/#/login`,302);}
  return env.ASSETS.fetch(req);
}

async function scheduled(event:any,env:Env){ const now=nowIso(); await env.DB.prepare("UPDATE articles SET status='published',published_at=COALESCE(published_at,scheduled_at),updated_at=CURRENT_TIMESTAMP WHERE status='scheduled' AND scheduled_at IS NOT NULL AND scheduled_at<=?").bind(now).run(); await env.DB.prepare('DELETE FROM sessions WHERE expires_at<?').bind(Math.floor(Date.now()/1000)).run(); await env.DB.prepare('DELETE FROM rate_limits WHERE expires_at<?').bind(Math.floor(Date.now()/1000)).run(); if(event.cron==='0 2 * * *'){const state=await env.DB.prepare('SELECT key,value_json,version,updated_at FROM app_state').all<any>(),articles=await env.DB.prepare('SELECT * FROM articles').all<any>(),products=await env.DB.prepare('SELECT * FROM products').all<any>(),jobs=await env.DB.prepare('SELECT * FROM jobs').all<any>(); const key=`${env.BACKUP_PREFIX||'backups'}/${new Date().toISOString().slice(0,10)}/content-${Date.now()}.json`; await env.MEDIA.put(key,JSON.stringify({exported_at:nowIso(),state:state.results||[],articles:articles.results||[],products:products.results||[],jobs:jobs.results||[]})); }
}

export default { async fetch(req:Request,env:Env){ try{return withSecurity(await route(req,env),new URL(req.url).pathname)}catch(e:any){console.error('AINFO worker error',e);return withSecurity(json({error:'internal_error',message:'Terjadi kesalahan server.'},500),new URL(req.url).pathname)} }, scheduled };
