import previousWorker from './v14_10.js';

const VERSION='14.11.0';
const VIDEO_CSS='<link rel="stylesheet" href="/video-v14.9.css?v=20260917b">';
const VIDEO_JS='<script src="/video-v14.9.js?v=20260917b"></script>';

function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}})}
function cookies(req){const out={};for(const part of (req.headers.get('cookie')||'').split(';')){const i=part.indexOf('=');if(i>0)out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim())}return out}
function safeEq(a,b){a=String(a||'');b=String(b||'');if(!a||!b||a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
function csrfOk(req){if(['GET','HEAD','OPTIONS'].includes(req.method))return true;return safeEq(cookies(req).ainfo_csrf,req.headers.get('x-csrf-token'))}
async function currentUser(req,env,ctx){const u=new URL(req.url);u.pathname='/api/auth/me';u.search='';const probe=new Request(u.toString(),{method:'GET',headers:req.headers});const r=await previousWorker.fetch(probe,env,ctx);if(!r.ok)return null;const d=await r.json().catch(()=>({}));return d.user||null}
function cleanMediaToken(v){const s=String(v||'').trim().slice(0,1000);if(!s)return'';if(/^sticker:(like|love|haha|wow|sad|angry)$/i.test(s))return s.toLowerCase();if(/^custom:[a-z0-9-]{1,120}$/i.test(s))return s;if(/^gif:https%3A%2F%2F/i.test(s)||/^gif:https:\/\//i.test(s))return s;return s.length<=20?s:''}

async function videoCommentsGet(req,env){const u=new URL(req.url),videoId=String(u.searchParams.get('video_id')||'').trim();if(!videoId)return json({comments:[],total:0});const rows=await env.DB.prepare(`SELECT c.id,c.video_id,c.user_id,c.parent_id,c.body,c.media_token,c.created_at,u.username,u.full_name,u.avatar_url FROM video_comments c JOIN users u ON u.id=c.user_id WHERE c.video_id=? AND c.status='published' ORDER BY c.created_at ASC LIMIT 400`).bind(videoId).all();const reactionRows=await env.DB.prepare(`SELECT r.comment_id,r.reaction,COUNT(*) count FROM video_comment_reactions r JOIN video_comments c ON c.id=r.comment_id WHERE c.video_id=? AND c.status='published' GROUP BY r.comment_id,r.reaction`).bind(videoId).all();const map=new Map();for(const r of reactionRows.results||[]){const id=String(r.comment_id);if(!map.has(id))map.set(id,{});map.get(id)[r.reaction]=Number(r.count||0)}const comments=(rows.results||[]).map(c=>{const reactions=map.get(String(c.id))||{};return{...c,reactions,reaction_total:Object.values(reactions).reduce((s,n)=>s+Number(n||0),0)}});return json({ok:true,comments,total:comments.length})}

async function videoCommentsPost(req,env,ctx){if(!csrfOk(req))return json({error:'csrf_failed',message:'Token keamanan tidak valid.'},403);const user=await currentUser(req,env,ctx);if(!user)return json({error:'unauthorized',message:'Silakan login terlebih dahulu.'},401);const d=await req.json().catch(()=>({}));const videoId=String(d.video_id||'').trim().slice(0,80),body=String(d.body||'').trim().slice(0,2000),media=cleanMediaToken(d.media_token),parent=d.parent_id?Number(d.parent_id):null;if(!videoId||(!body&&!media))return json({error:'invalid_comment',message:'Komentar kosong.'},400);if(parent){const p=await env.DB.prepare("SELECT id FROM video_comments WHERE id=? AND video_id=? AND status='published'").bind(parent,videoId).first();if(!p)return json({error:'invalid_parent'},400)}const run=await env.DB.prepare('INSERT INTO video_comments(video_id,user_id,parent_id,body,media_token,status) VALUES(?,?,?,?,?,?)').bind(videoId,Number(user.id),parent,body,media,'published').run();return json({ok:true,id:Number(run.meta?.last_row_id||run.meta?.lastRowId||0)},201)}

async function videoCommentReaction(req,env,ctx){if(!csrfOk(req))return json({error:'csrf_failed'},403);const user=await currentUser(req,env,ctx);if(!user)return json({error:'unauthorized',message:'Silakan login terlebih dahulu.'},401);const d=await req.json().catch(()=>({})),commentId=Number(d.comment_id),reaction=String(d.reaction||'like');if(!commentId||!['like','love','haha','wow','sad','angry'].includes(reaction))return json({error:'invalid_reaction'},400);const exists=await env.DB.prepare("SELECT id FROM video_comments WHERE id=? AND status='published'").bind(commentId).first();if(!exists)return json({error:'comment_not_found'},404);await env.DB.prepare(`INSERT INTO video_comment_reactions(comment_id,user_id,reaction) VALUES(?,?,?) ON CONFLICT(comment_id,user_id) DO UPDATE SET reaction=excluded.reaction,updated_at=CURRENT_TIMESTAMP`).bind(commentId,Number(user.id),reaction).run();const rows=await env.DB.prepare('SELECT reaction,COUNT(*) count FROM video_comment_reactions WHERE comment_id=? GROUP BY reaction').bind(commentId).all();const total=(rows.results||[]).reduce((s,x)=>s+Number(x.count||0),0);return json({ok:true,total,counts:rows.results||[]})}

async function videoReactionsGet(req,env){const u=new URL(req.url),videoId=String(u.searchParams.get('video_id')||'').trim();if(!videoId)return json({counts:[]});const rows=await env.DB.prepare("SELECT reaction,COUNT(*) count FROM reactions WHERE target_type='video' AND target_id=? GROUP BY reaction").bind(videoId).all();return json({ok:true,counts:rows.results||[]})}

function shouldInject(req,res){return req.method==='GET'&&String(res.headers.get('content-type')||'').toLowerCase().includes('text/html')}
async function injectVideoAssets(req,res){if(!shouldInject(req,res))return res;let body=await res.text();if(!body.includes('/video-v14.9.css'))body=/<\/head>/i.test(body)?body.replace(/<\/head>/i,`${VIDEO_CSS}</head>`):VIDEO_CSS+body;if(!body.includes('/video-v14.9.js'))body=/<\/body>/i.test(body)?body.replace(/<\/body>/i,`${VIDEO_JS}</body>`):body+VIDEO_JS;const headers=new Headers(res.headers);headers.delete('content-length');headers.set('x-ainfo-version',VERSION);headers.set('x-ainfo-video-ui','3-column-engagement');return new Response(body,{status:res.status,statusText:res.statusText,headers})}

async function route(req,env,ctx){const url=new URL(req.url),p=url.pathname;if(p==='/api/video/comments'&&req.method==='GET')return videoCommentsGet(req,env);if(p==='/api/video/comments'&&req.method==='POST')return videoCommentsPost(req,env,ctx);if(p==='/api/video/comments/reaction'&&req.method==='POST')return videoCommentReaction(req,env,ctx);if(p==='/api/video/reactions'&&req.method==='GET')return videoReactionsGet(req,env);const res=await previousWorker.fetch(req,env,ctx);return injectVideoAssets(req,res)}

export default{async fetch(req,env,ctx){try{return await route(req,env,ctx)}catch(error){console.error('AINFO V14.11 video wrapper error',error);return previousWorker.fetch(req,env,ctx)}},async scheduled(event,env,ctx){if(typeof previousWorker.scheduled==='function')return previousWorker.scheduled(event,env,ctx)}};
