import previousWorker from './v14_11.js';

const VERSION='14.12.0';
const ENG_CSS='<link rel="stylesheet" href="/engagement-v14.12.css?v=20260917a">';
const ENG_JS='<script src="/engagement-v14.12.js?v=20260917a"></script>';

function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}})}
function cookies(req){const out={};for(const part of (req.headers.get('cookie')||'').split(';')){const i=part.indexOf('=');if(i>0)out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim())}return out}
function safeEq(a,b){a=String(a||'');b=String(b||'');if(!a||!b||a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
function csrfOk(req){if(['GET','HEAD','OPTIONS'].includes(req.method))return true;return safeEq(cookies(req).ainfo_csrf,req.headers.get('x-csrf-token'))}
async function currentUser(req,env,ctx){const u=new URL(req.url);u.pathname='/api/auth/me';u.search='';const probe=new Request(u.toString(),{method:'GET',headers:req.headers});const r=await previousWorker.fetch(probe,env,ctx);if(!r.ok)return null;const d=await r.json().catch(()=>({}));return d.user||null}
function cleanMediaToken(v){const s=String(v||'').trim().slice(0,1200);if(!s)return'';if(/^sticker:(like|love|haha|wow|sad|angry)$/i.test(s))return s.toLowerCase();if(/^custom:[a-z0-9-]{1,120}$/i.test(s))return s;if(/^gif:https%3A%2F%2F/i.test(s)||/^gif:https:\/\//i.test(s))return s;return s.length<=32?s:''}

async function shopEngagementGet(req,env){
  const u=new URL(req.url),productId=Number(u.searchParams.get('product_id')||0);if(!productId)return json({error:'invalid_product'},400);
  const product=await env.DB.prepare("SELECT id,rating,COALESCE(rating_count,0) rating_count FROM products WHERE id=? AND status='active'").bind(productId).first();if(!product)return json({error:'product_not_found'},404);
  const rows=await env.DB.prepare(`SELECT c.id,c.product_id,c.user_id,c.parent_id,c.kind,c.rating,c.body,c.media_token,c.created_at,u.username,u.full_name,u.avatar_url FROM product_comments c JOIN users u ON u.id=c.user_id WHERE c.product_id=? AND c.status='published' ORDER BY CASE WHEN c.parent_id IS NULL THEN 0 ELSE 1 END,c.created_at ASC LIMIT 800`).bind(productId).all();
  const rx=await env.DB.prepare(`SELECT r.comment_id,r.reaction,COUNT(*) count FROM product_comment_reactions r JOIN product_comments c ON c.id=r.comment_id WHERE c.product_id=? AND c.status='published' GROUP BY r.comment_id,r.reaction`).bind(productId).all();
  const map=new Map();for(const r of rx.results||[]){const id=String(r.comment_id);if(!map.has(id))map.set(id,{});map.get(id)[r.reaction]=Number(r.count||0)}
  const comments=(rows.results||[]).map(c=>{const reactions=map.get(String(c.id))||{};return{...c,reactions,reaction_total:Object.values(reactions).reduce((s,n)=>s+Number(n||0),0)}});
  const stats=await env.DB.prepare(`SELECT COUNT(*) review_count,COALESCE(AVG(rating),0) rating FROM product_comments WHERE product_id=? AND kind='review' AND parent_id IS NULL AND status='published' AND rating BETWEEN 1 AND 5`).bind(productId).first();
  const discussions=await env.DB.prepare(`SELECT COUNT(*) n FROM product_comments WHERE product_id=? AND kind='discussion' AND parent_id IS NULL AND status='published'`).bind(productId).first();
  const breakdownRows=await env.DB.prepare(`SELECT rating,COUNT(*) n FROM product_comments WHERE product_id=? AND kind='review' AND parent_id IS NULL AND status='published' AND rating BETWEEN 1 AND 5 GROUP BY rating`).bind(productId).all();const breakdown={1:0,2:0,3:0,4:0,5:0};for(const r of breakdownRows.results||[])breakdown[Number(r.rating)]=Number(r.n||0);
  const reviewCount=Number(stats?.review_count||0),rating=Number(stats?.rating||0);return json({ok:true,version:VERSION,summary:{rating,rating_count:reviewCount,review_count:reviewCount,discussion_count:Number(discussions?.n||0),breakdown},comments});
}

async function recalcProductRating(env,productId){const s=await env.DB.prepare(`SELECT COUNT(*) n,COALESCE(AVG(rating),0) avg FROM product_comments WHERE product_id=? AND kind='review' AND parent_id IS NULL AND status='published' AND rating BETWEEN 1 AND 5`).bind(productId).first();await env.DB.prepare('UPDATE products SET rating=?,rating_count=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(Number(s?.avg||0),Number(s?.n||0),productId).run()}

async function shopCommentPost(req,env,ctx){
  if(!csrfOk(req))return json({error:'csrf_failed',message:'Token keamanan tidak valid.'},403);const user=await currentUser(req,env,ctx);if(!user)return json({error:'unauthorized',message:'Silakan login terlebih dahulu.'},401);
  const d=await req.json().catch(()=>({})),productId=Number(d.product_id),parent=d.parent_id?Number(d.parent_id):null,body=String(d.body||'').trim().slice(0,2000),media=cleanMediaToken(d.media_token),kind=d.kind==='review'?'review':'discussion',rating=d.rating==null?null:Number(d.rating);
  if(!productId||(!body&&!media))return json({error:'invalid_comment',message:'Komentar kosong.'},400);const product=await env.DB.prepare("SELECT id FROM products WHERE id=? AND status='active'").bind(productId).first();if(!product)return json({error:'product_not_found'},404);
  let finalKind=kind,finalRating=null;if(parent){const p=await env.DB.prepare("SELECT id,kind FROM product_comments WHERE id=? AND product_id=? AND status='published'").bind(parent,productId).first();if(!p)return json({error:'invalid_parent'},400);finalKind=String(p.kind)==='review'?'review':'discussion';finalRating=null}else if(kind==='review'){if(!rating||rating<1||rating>5)return json({error:'invalid_rating',message:'Rating wajib 1–5 bintang.'},400);finalRating=rating}
  const run=await env.DB.prepare('INSERT INTO product_comments(product_id,user_id,parent_id,kind,rating,body,media_token,status) VALUES(?,?,?,?,?,?,?,?)').bind(productId,Number(user.id),parent,finalKind,finalRating,body,media,'published').run();if(!parent&&finalKind==='review')await recalcProductRating(env,productId);return json({ok:true,id:Number(run.meta?.last_row_id||run.meta?.lastRowId||0)},201)
}

async function shopCommentReaction(req,env,ctx){
  if(!csrfOk(req))return json({error:'csrf_failed'},403);const user=await currentUser(req,env,ctx);if(!user)return json({error:'unauthorized',message:'Silakan login terlebih dahulu.'},401);const d=await req.json().catch(()=>({})),commentId=Number(d.comment_id),reaction=String(d.reaction||'like');if(!commentId||!['like','love','haha','wow','sad','angry'].includes(reaction))return json({error:'invalid_reaction'},400);const exists=await env.DB.prepare("SELECT id FROM product_comments WHERE id=? AND status='published'").bind(commentId).first();if(!exists)return json({error:'comment_not_found'},404);await env.DB.prepare(`INSERT INTO product_comment_reactions(comment_id,user_id,reaction) VALUES(?,?,?) ON CONFLICT(comment_id,user_id) DO UPDATE SET reaction=excluded.reaction,updated_at=CURRENT_TIMESTAMP`).bind(commentId,Number(user.id),reaction).run();const rows=await env.DB.prepare('SELECT reaction,COUNT(*) count FROM product_comment_reactions WHERE comment_id=? GROUP BY reaction').bind(commentId).all();return json({ok:true,counts:rows.results||[],total:(rows.results||[]).reduce((s,x)=>s+Number(x.count||0),0)})
}

function giphyKey(env){return String(env.GIPHY_API_KEY||env.GIPHY_API_KEY_PUBLIC||'').trim()}
async function giphyConfig(env){const key=giphyKey(env);return json({ok:true,version:VERSION,configured:Boolean(key),apiKey:key?'proxy':'',rating:'pg',language:'id'})}
async function giphyProxy(req,env){const key=giphyKey(env);if(!key)return json({error:'giphy_not_configured',message:'Set GIPHY_API_KEY sebagai Cloudflare Secret.'},503);const u=new URL(req.url),mode=u.searchParams.get('mode')==='search'?'search':'trending',q=String(u.searchParams.get('q')||'').trim().slice(0,50),limit=Math.max(1,Math.min(30,Number(u.searchParams.get('limit')||24)));const target=new URL(`https://api.giphy.com/v1/gifs/${mode}`);target.searchParams.set('api_key',key);target.searchParams.set('limit',String(limit));target.searchParams.set('rating','pg');target.searchParams.set('bundle','messaging_non_clips');if(mode==='search'){target.searchParams.set('q',q||'reaction');target.searchParams.set('lang','id')}const r=await fetch(target.toString(),{headers:{accept:'application/json'}});const text=await r.text();return new Response(text,{status:r.status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=120'}})}

function shouldInject(req,res){return req.method==='GET'&&String(res.headers.get('content-type')||'').toLowerCase().includes('text/html')}
async function injectAssets(req,res){if(!shouldInject(req,res))return res;let body=await res.text();if(!body.includes('/engagement-v14.12.css'))body=/<\/head>/i.test(body)?body.replace(/<\/head>/i,`${ENG_CSS}</head>`):ENG_CSS+body;if(!body.includes('/engagement-v14.12.js'))body=/<\/body>/i.test(body)?body.replace(/<\/body>/i,`${ENG_JS}</body>`):body+ENG_JS;const headers=new Headers(res.headers);headers.delete('content-length');headers.set('x-ainfo-version',VERSION);headers.set('x-ainfo-engagement','article-video-shop');return new Response(body,{status:res.status,statusText:res.statusText,headers})}

async function route(req,env,ctx){const u=new URL(req.url),p=u.pathname;if(p==='/api/shop/engagement'&&req.method==='GET')return shopEngagementGet(req,env);if(p==='/api/shop/comment'&&req.method==='POST')return shopCommentPost(req,env,ctx);if(p==='/api/shop/comment/reaction'&&req.method==='POST')return shopCommentReaction(req,env,ctx);if(p==='/api/public/giphy-config'&&req.method==='GET')return giphyConfig(env);if(p==='/api/giphy'&&req.method==='GET')return giphyProxy(req,env);const res=await previousWorker.fetch(req,env,ctx);return injectAssets(req,res)}

export default{async fetch(req,env,ctx){try{return await route(req,env,ctx)}catch(error){console.error('AINFO V14.12 unified engagement error',error);return previousWorker.fetch(req,env,ctx)}},async scheduled(event,env,ctx){if(typeof previousWorker.scheduled==='function')return previousWorker.scheduled(event,env,ctx)}};
