import previousWorker from './v14_16.js';

const VERSION='14.17.0';
const VIDEO_CSS='<link rel="stylesheet" href="/video-sources-v14.17.css?v=20260917a">';
const VIDEO_JS='<script src="/video-sources-v14.17.js?v=20260917a"></script>';
const ADMIN_JS='<script src="/admin-video-sources-v14.17.js?v=20260917a"></script>';

function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-ainfo-version':VERSION,...headers}})}
function site(env){return String(env.DOMAIN||'https://www.ainfo.web.id').replace(/\/$/,'')}
function cookies(req){const out={};for(const p of String(req.headers.get('cookie')||'').split(';')){const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return out}
function timingSafe(a,b){a=String(a||'');b=String(b||'');if(!a||!b||a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
function csrfOk(req){if(['GET','HEAD','OPTIONS'].includes(req.method))return true;return timingSafe(cookies(req).ainfo_csrf||'',req.headers.get('x-csrf-token')||'')}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function safeJson(v,f={}){try{return JSON.parse(v)}catch{return f}}
function nowIso(){return new Date().toISOString()}
function bool(v){return v===true||v===1||v==='1'||v==='true'}
function int(v,d=0){const n=Number(v);return Number.isFinite(n)?Math.trunc(n):d}
function cleanProvider(v){return ['youtube','tiktok','dailymotion','ainfo'].includes(String(v))?String(v):''}
function isoDurationSeconds(v){const m=String(v||'').match(/^P(?:(\d+)D)?(?:T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+(?:\.\d+)?)S)?)?$/i);if(!m)return 0;return int(m[1])*86400+int(m[2])*3600+int(m[3])*60+Math.round(Number(m[4]||0))}
function b64(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s)}
function unb64(s){const raw=atob(s);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
async function cryptoKey(env){const secret=String(env.VIDEO_TOKEN_ENCRYPTION_KEY||'');if(!secret)return null;const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(secret));return crypto.subtle.importKey('raw',digest,{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function encryptToken(env,value){if(!value)return'';const key=await cryptoKey(env);if(!key)throw new Error('VIDEO_TOKEN_ENCRYPTION_KEY belum diatur');const iv=crypto.getRandomValues(new Uint8Array(12));const enc=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(String(value))));return `${b64(iv)}.${b64(enc)}`}
async function decryptToken(env,value){if(!value)return'';const key=await cryptoKey(env);if(!key)throw new Error('VIDEO_TOKEN_ENCRYPTION_KEY belum diatur');const [a,b]=String(value).split('.');const out=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(a)},key,unb64(b));return new TextDecoder().decode(out)}

async function adminAllowed(req,env,ctx){try{const u=new URL(req.url);u.pathname='/api/admin/metrics';u.search='';const r=await previousWorker.fetch(new Request(u,{method:'GET',headers:req.headers}),env,ctx);return r.status===200}catch{return false}}
async function requireAdmin(req,env,ctx){if(!(await adminAllowed(req,env,ctx)))return json({error:'forbidden'},403);if(!csrfOk(req))return json({error:'csrf_failed',message:'Muat ulang halaman admin.'},403);return null}

function catalogOut(r){return{ id:Number(r.id),provider:r.provider,external_id:r.external_id,source_id:r.source_id?Number(r.source_id):null,kind:r.kind,title:r.title,description:r.description||'',thumbnail:r.thumbnail_url||'',embed_url:r.embed_url||'',watch_url:r.watch_url||'',duration:Number(r.duration_seconds||0),width:Number(r.width||0),height:Number(r.height||0),author:r.author_name||'',author_url:r.author_url||'',published_at:r.published_at||'',stats:safeJson(r.stats_json||'{}',{}),tags:safeJson(r.tags_json||'[]',[]),status:r.status||'review'} }
async function upsertVideo(env,source,v){const status=source.auto_publish?'published':'review';await env.DB.prepare(`INSERT INTO video_catalog(provider,external_id,source_id,kind,title,description,thumbnail_url,embed_url,watch_url,duration_seconds,width,height,author_name,author_url,published_at,stats_json,tags_json,status,updated_at)
VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)
ON CONFLICT(provider,external_id) DO UPDATE SET source_id=excluded.source_id,kind=excluded.kind,title=excluded.title,description=excluded.description,thumbnail_url=excluded.thumbnail_url,embed_url=excluded.embed_url,watch_url=excluded.watch_url,duration_seconds=excluded.duration_seconds,width=excluded.width,height=excluded.height,author_name=excluded.author_name,author_url=excluded.author_url,published_at=COALESCE(excluded.published_at,video_catalog.published_at),stats_json=excluded.stats_json,tags_json=excluded.tags_json,updated_at=CURRENT_TIMESTAMP`).bind(source.provider,String(v.external_id),source.id,v.kind||'video',String(v.title||'Video'),String(v.description||''),String(v.thumbnail||''),String(v.embed_url||''),String(v.watch_url||''),int(v.duration),int(v.width),int(v.height),String(v.author||source.name||''),String(v.author_url||''),v.published_at||null,JSON.stringify(v.stats||{}),JSON.stringify(v.tags||[]),status).run()}

async function syncYouTube(env,source){const key=String(env.YOUTUBE_API_KEY||'').trim();if(!key)throw new Error('YOUTUBE_API_KEY belum diatur');const channel=String(source.external_id||'').trim();if(!channel)throw new Error('Channel ID kosong');const cUrl=new URL('https://www.googleapis.com/youtube/v3/channels');cUrl.searchParams.set('part','snippet,contentDetails');cUrl.searchParams.set('id',channel);cUrl.searchParams.set('key',key);const cr=await fetch(cUrl);const cd=await cr.json();if(!cr.ok||!cd.items?.[0])throw new Error(cd.error?.message||'Channel YouTube tidak ditemukan');const c=cd.items[0];const playlist=c.contentDetails?.relatedPlaylists?.uploads;if(!playlist)throw new Error('Uploads playlist tidak ditemukan');const pUrl=new URL('https://www.googleapis.com/youtube/v3/playlistItems');pUrl.searchParams.set('part','snippet,contentDetails');pUrl.searchParams.set('playlistId',playlist);pUrl.searchParams.set('maxResults','20');pUrl.searchParams.set('key',key);const pr=await fetch(pUrl);const pd=await pr.json();if(!pr.ok)throw new Error(pd.error?.message||'Gagal membaca video YouTube');const ids=(pd.items||[]).map(x=>x.contentDetails?.videoId||x.snippet?.resourceId?.videoId).filter(Boolean);let details=new Map();if(ids.length){const vUrl=new URL('https://www.googleapis.com/youtube/v3/videos');vUrl.searchParams.set('part','contentDetails,statistics,snippet,liveStreamingDetails');vUrl.searchParams.set('id',ids.join(','));vUrl.searchParams.set('key',key);const vr=await fetch(vUrl);const vd=await vr.json();if(vr.ok)details=new Map((vd.items||[]).map(x=>[x.id,x]))}
let n=0;for(const item of pd.items||[]){const id=item.contentDetails?.videoId||item.snippet?.resourceId?.videoId;if(!id)continue;const d=details.get(id)||{};const dur=isoDurationSeconds(d.contentDetails?.duration);const isLive=Boolean(d.snippet?.liveBroadcastContent&&d.snippet.liveBroadcastContent!=='none');const kind=isLive?'live':dur>0&&dur<=180?'short':'video';const cfg=safeJson(source.config_json||'{}',{});if(cfg.shorts_only&&kind!=='short')continue;await upsertVideo(env,source,{external_id:id,kind,title:d.snippet?.title||item.snippet?.title,description:d.snippet?.description||item.snippet?.description,thumbnail:d.snippet?.thumbnails?.maxres?.url||d.snippet?.thumbnails?.high?.url||item.snippet?.thumbnails?.high?.url||'',embed_url:`https://www.youtube-nocookie.com/embed/${encodeURIComponent(id)}?playsinline=1&rel=0`,watch_url:`https://www.youtube.com/watch?v=${encodeURIComponent(id)}`,duration:dur,author:d.snippet?.channelTitle||c.snippet?.title||source.name,author_url:`https://www.youtube.com/channel/${channel}`,published_at:d.snippet?.publishedAt||item.contentDetails?.videoPublishedAt||item.snippet?.publishedAt||null,stats:{views:int(d.statistics?.viewCount),likes:int(d.statistics?.likeCount),comments:int(d.statistics?.commentCount)},tags:d.snippet?.tags||[]});n++}return n}

async function syncDailymotion(env,source){const token=String(env.DAILYMOTION_ACCESS_TOKEN||'').trim();if(!token)throw new Error('DAILYMOTION_ACCESS_TOKEN belum diatur');const type=source.source_type==='playlist'?'playlists':'profiles';const u=new URL(`https://api.dailymotion.com/v2/${type}/${encodeURIComponent(source.external_id)}/videos`);u.searchParams.set('page_size','20');u.searchParams.set('fields','video_id,title,description,published_at,created_at,thumbnail,embedding,video_url,profile,tags,hashtags');const r=await fetch(u,{headers:{authorization:`Bearer ${token}`,accept:'application/json'}});const d=await r.json();if(!r.ok)throw new Error(d.error?.message||'Dailymotion API gagal');const rows=Array.isArray(d.data)?d.data:Array.isArray(d.list)?d.list:Array.isArray(d.items)?d.items:[];let n=0;for(const x of rows){const id=x.video_id||x.id;if(!id)continue;const thumb=x.thumbnail?.url||x.thumbnail||x.first_frame?.url||'';const author=x.profile?.name||x.profile?.display_name||source.name;await upsertVideo(env,source,{external_id:id,kind:'video',title:x.title,description:x.description,thumbnail:thumb,embed_url:x.embedding?.embed_url||`https://www.dailymotion.com/embed/video/${encodeURIComponent(id)}`,watch_url:x.video_url||`https://www.dailymotion.com/video/${encodeURIComponent(id)}`,author,author_url:'',published_at:x.published_at||x.created_at||null,tags:x.tags||x.hashtags||[]});n++}return n}

async function tiktokConnection(env){return env.DB.prepare("SELECT * FROM video_oauth_connections WHERE provider='tiktok' LIMIT 1").first()}
async function refreshTikTok(env,row){if(!row)return null;const expires=Date.parse(row.expires_at||'');if(expires&&expires-Date.now()>10*60*1000)return row;const refresh=await decryptToken(env,row.refresh_token_enc);if(!refresh)return row;const body=new URLSearchParams({client_key:String(env.TIKTOK_CLIENT_KEY||''),client_secret:String(env.TIKTOK_CLIENT_SECRET||''),grant_type:'refresh_token',refresh_token:refresh});const r=await fetch('https://open.tiktokapis.com/v2/oauth/token/',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});const d=await r.json();if(!r.ok||!d.access_token)throw new Error(d.error_description||d.error?.message||'Refresh token TikTok gagal');const accessEnc=await encryptToken(env,d.access_token),refreshEnc=await encryptToken(env,d.refresh_token||refresh);const exp=new Date(Date.now()+int(d.expires_in,86400)*1000).toISOString(),rexp=new Date(Date.now()+int(d.refresh_expires_in,31536000)*1000).toISOString();await env.DB.prepare("UPDATE video_oauth_connections SET access_token_enc=?,refresh_token_enc=?,expires_at=?,refresh_expires_at=?,updated_at=CURRENT_TIMESTAMP WHERE provider='tiktok'").bind(accessEnc,refreshEnc,exp,rexp).run();return tiktokConnection(env)}
async function syncTikTok(env,source){if(source.source_type==='url'){const u=new URL('https://www.tiktok.com/oembed');u.searchParams.set('url',source.external_id);const r=await fetch(u);const d=await r.json();if(!r.ok)throw new Error('TikTok oEmbed gagal');const m=String(source.external_id).match(/\/video\/(\d+)/);const id=m?.[1]||source.external_id;await upsertVideo(env,source,{external_id:id,kind:'short',title:d.title||'TikTok Video',description:d.title||'',thumbnail:d.thumbnail_url||'',embed_url:`https://www.tiktok.com/player/v1/${encodeURIComponent(id)}`,watch_url:source.external_id,author:d.author_name||source.name,author_url:d.author_url||'',published_at:null});return 1}
let conn=await tiktokConnection(env);if(!conn)throw new Error('TikTok belum dihubungkan melalui Admin');conn=await refreshTikTok(env,conn);const token=await decryptToken(env,conn.access_token_enc);const fields='id,title,video_description,duration,cover_image_url,embed_link,share_url,create_time,height,width,like_count,comment_count,share_count,view_count';const u=`https://open.tiktokapis.com/v2/video/list/?fields=${encodeURIComponent(fields)}`;const r=await fetch(u,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({max_count:20})});const d=await r.json();if(!r.ok||d.error?.code&&d.error.code!=='ok')throw new Error(d.error?.message||'TikTok Display API gagal');let n=0;for(const x of d.data?.videos||[]){await upsertVideo(env,source,{external_id:x.id,kind:'short',title:x.title||x.video_description||'TikTok Video',description:x.video_description||'',thumbnail:x.cover_image_url||'',embed_url:x.embed_link||`https://www.tiktok.com/player/v1/${x.id}`,watch_url:x.share_url||'',duration:int(x.duration),width:int(x.width),height:int(x.height),author:conn.display_name||source.name,published_at:x.create_time?new Date(Number(x.create_time)*1000).toISOString():null,stats:{views:int(x.view_count),likes:int(x.like_count),comments:int(x.comment_count),shares:int(x.share_count)}});n++}return n}

async function syncSource(env,source){let n=0;try{if(source.provider==='youtube')n=await syncYouTube(env,source);else if(source.provider==='dailymotion')n=await syncDailymotion(env,source);else if(source.provider==='tiktok')n=await syncTikTok(env,source);else n=0;await env.DB.prepare("UPDATE video_sources SET last_sync_at=CURRENT_TIMESTAMP,last_error='',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(source.id).run();await env.DB.prepare("INSERT INTO video_sync_log(source_id,provider,status,imported_count,message) VALUES(?,?,?,?,?)").bind(source.id,source.provider,'success',n,'').run();return{ok:true,count:n}}catch(e){const msg=String(e?.message||e).slice(0,500);await env.DB.prepare("UPDATE video_sources SET last_sync_at=CURRENT_TIMESTAMP,last_error=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(msg,source.id).run();await env.DB.prepare("INSERT INTO video_sync_log(source_id,provider,status,imported_count,message) VALUES(?,?,?,?,?)").bind(source.id,source.provider,'error',0,msg).run();return{ok:false,count:0,error:msg}}}
async function syncAll(env){const rows=await env.DB.prepare('SELECT * FROM video_sources WHERE enabled=1 ORDER BY id ASC').all();const out=[];for(const s of rows.results||[])out.push({id:s.id,provider:s.provider,...await syncSource(env,s)});return out}

async function feed(req,env){const u=new URL(req.url),limit=Math.max(1,Math.min(100,int(u.searchParams.get('limit'),36))),provider=cleanProvider(u.searchParams.get('provider'));let sql="SELECT * FROM video_catalog WHERE status='published'",bind=[];if(provider){sql+=' AND provider=?';bind.push(provider)}sql+=' ORDER BY COALESCE(published_at,created_at) DESC,id DESC LIMIT ?';bind.push(limit);const rows=await env.DB.prepare(sql).bind(...bind).all();return json({ok:true,version:VERSION,videos:(rows.results||[]).map(catalogOut)},{},{'cache-control':'public, max-age=30, s-maxage=60'})}
async function oneVideo(id,env){const row=await env.DB.prepare("SELECT * FROM video_catalog WHERE id=? AND status='published' LIMIT 1").bind(Number(id)).first();return row?json({ok:true,video:catalogOut(row)}):json({error:'video_not_found'},404)}

async function adminSources(req,env,ctx){const deny=await requireAdmin(req,env,ctx);if(deny)return deny;if(req.method==='GET'){const rows=await env.DB.prepare('SELECT * FROM video_sources ORDER BY id DESC').all();const conn=await tiktokConnection(env);return json({ok:true,version:VERSION,sources:rows.results||[],integrations:{youtube:Boolean(env.YOUTUBE_API_KEY),dailymotion:Boolean(env.DAILYMOTION_ACCESS_TOKEN),tiktokApp:Boolean(env.TIKTOK_CLIENT_KEY&&env.TIKTOK_CLIENT_SECRET&&env.VIDEO_TOKEN_ENCRYPTION_KEY),tiktokConnected:Boolean(conn)}})}const d=await req.json().catch(()=>({})),provider=cleanProvider(d.provider);if(!provider)return json({error:'invalid_provider'},400);const name=String(d.name||provider).trim().slice(0,120),type=String(d.source_type||'channel').trim().slice(0,30),external=String(d.external_id||'').trim().slice(0,800);if(!external)return json({error:'external_id_required'},400);const cfg=JSON.stringify({shorts_only:bool(d.shorts_only)});if(d.id){await env.DB.prepare('UPDATE video_sources SET provider=?,name=?,source_type=?,external_id=?,config_json=?,enabled=?,auto_publish=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(provider,name,type,external,cfg,bool(d.enabled)?1:0,bool(d.auto_publish)?1:0,Number(d.id)).run()}else{await env.DB.prepare('INSERT INTO video_sources(provider,name,source_type,external_id,config_json,enabled,auto_publish) VALUES(?,?,?,?,?,?,?)').bind(provider,name,type,external,cfg,bool(d.enabled)?1:0,bool(d.auto_publish)?1:0).run()}return json({ok:true})}
async function deleteSource(req,env,ctx,id){const deny=await requireAdmin(req,env,ctx);if(deny)return deny;await env.DB.prepare('DELETE FROM video_sources WHERE id=?').bind(Number(id)).run();return json({ok:true})}
async function adminSync(req,env,ctx){const deny=await requireAdmin(req,env,ctx);if(deny)return deny;const d=await req.json().catch(()=>({}));if(d.id){const source=await env.DB.prepare('SELECT * FROM video_sources WHERE id=?').bind(Number(d.id)).first();if(!source)return json({error:'source_not_found'},404);return json({ok:true,result:await syncSource(env,source)})}return json({ok:true,results:await syncAll(env)})}
async function setVideoStatus(req,env,ctx){const deny=await requireAdmin(req,env,ctx);if(deny)return deny;const d=await req.json().catch(()=>({})),status=['review','published','hidden'].includes(String(d.status))?String(d.status):'';if(!status||!d.id)return json({error:'invalid_status'},400);await env.DB.prepare('UPDATE video_catalog SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(status,Number(d.id)).run();return json({ok:true})}
async function adminCatalog(req,env,ctx){const deny=await requireAdmin(req,env,ctx);if(deny)return deny;const rows=await env.DB.prepare('SELECT * FROM video_catalog ORDER BY COALESCE(published_at,created_at) DESC,id DESC LIMIT 300').all();return json({ok:true,videos:(rows.results||[]).map(catalogOut)})}

async function tiktokConnect(req,env,ctx){if(!(await adminAllowed(req,env,ctx)))return new Response('Forbidden',{status:403});if(!env.TIKTOK_CLIENT_KEY||!env.TIKTOK_CLIENT_SECRET||!env.VIDEO_TOKEN_ENCRYPTION_KEY)return new Response('TikTok secrets belum lengkap',{status:503});const state=crypto.randomUUID().replace(/-/g,'');const redirect=`${site(env)}/api/video/tiktok/callback`;const u=new URL('https://www.tiktok.com/v2/auth/authorize/');u.searchParams.set('client_key',env.TIKTOK_CLIENT_KEY);u.searchParams.set('scope','user.info.basic,video.list');u.searchParams.set('response_type','code');u.searchParams.set('redirect_uri',redirect);u.searchParams.set('state',state);return new Response(null,{status:302,headers:{location:u.toString(),'set-cookie':`ainfo_tiktok_state=${state}; Path=/api/video/tiktok/; Max-Age=600; HttpOnly; Secure; SameSite=Lax`}})}
async function tiktokCallback(req,env){const u=new URL(req.url),code=u.searchParams.get('code')||'',state=u.searchParams.get('state')||'',expected=cookies(req).ainfo_tiktok_state||'';if(!code||!timingSafe(state,expected))return new Response('TikTok OAuth state tidak valid',{status:400});const redirect=`${site(env)}/api/video/tiktok/callback`;const body=new URLSearchParams({client_key:String(env.TIKTOK_CLIENT_KEY||''),client_secret:String(env.TIKTOK_CLIENT_SECRET||''),code,grant_type:'authorization_code',redirect_uri:redirect});const r=await fetch('https://open.tiktokapis.com/v2/oauth/token/',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});const d=await r.json();if(!r.ok||!d.access_token)return new Response(`TikTok OAuth gagal: ${esc(d.error_description||d.error||'unknown')}`,{status:502});const accessEnc=await encryptToken(env,d.access_token),refreshEnc=await encryptToken(env,d.refresh_token||'');const exp=new Date(Date.now()+int(d.expires_in,86400)*1000).toISOString(),rexp=new Date(Date.now()+int(d.refresh_expires_in,31536000)*1000).toISOString();let display='',profile={};try{const ir=await fetch('https://open.tiktokapis.com/v2/user/info/?fields=open_id,display_name,avatar_url,profile_deep_link',{headers:{authorization:`Bearer ${d.access_token}`}});const idata=await ir.json();profile=idata.data?.user||{};display=profile.display_name||''}catch{}await env.DB.prepare(`INSERT INTO video_oauth_connections(provider,subject_id,display_name,access_token_enc,refresh_token_enc,expires_at,refresh_expires_at,scopes,profile_json) VALUES('tiktok',?,?,?,?,?,?,?,?) ON CONFLICT(provider) DO UPDATE SET subject_id=excluded.subject_id,display_name=excluded.display_name,access_token_enc=excluded.access_token_enc,refresh_token_enc=excluded.refresh_token_enc,expires_at=excluded.expires_at,refresh_expires_at=excluded.refresh_expires_at,scopes=excluded.scopes,profile_json=excluded.profile_json,updated_at=CURRENT_TIMESTAMP`).bind(String(d.open_id||profile.open_id||''),display,accessEnc,refreshEnc,exp,rexp,String(d.scope||''),JSON.stringify(profile)).run();return new Response(null,{status:302,headers:{location:`${site(env)}/admin/#video`, 'set-cookie':'ainfo_tiktok_state=; Path=/api/video/tiktok/; Max-Age=0; HttpOnly; Secure; SameSite=Lax'}})}

async function subscribeYouTube(env,source){if(source.provider!=='youtube')return;const body=new URLSearchParams({'hub.callback':`${site(env)}/api/video/websub/youtube`,'hub.topic':`https://www.youtube.com/feeds/videos.xml?channel_id=${source.external_id}`,'hub.mode':'subscribe','hub.verify':'async'});try{await fetch('https://pubsubhubbub.appspot.com/subscribe',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body})}catch{}}
async function websub(req,env,ctx){const u=new URL(req.url);if(req.method==='GET'){return new Response(u.searchParams.get('hub.challenge')||'',{status:200,headers:{'content-type':'text/plain'}})}const xml=await req.text();const channel=(xml.match(/<yt:channelId>([^<]+)<\/yt:channelId>/)||[])[1];if(channel){const s=await env.DB.prepare("SELECT * FROM video_sources WHERE provider='youtube' AND external_id=? AND enabled=1 LIMIT 1").bind(channel).first();if(s)ctx?.waitUntil?.(syncSource(env,s))}return new Response('',{status:204})}

function isHtml(req,res){return req.method==='GET'&&String(res.headers.get('content-type')||'').toLowerCase().includes('text/html')}
async function inject(req,res){if(!isHtml(req,res))return res;let body=await res.text();if(!body.includes('/video-sources-v14.17.css'))body=/<\/head>/i.test(body)?body.replace(/<\/head>/i,`${VIDEO_CSS}</head>`):VIDEO_CSS+body;if(!body.includes('/video-sources-v14.17.js'))body=/<\/body>/i.test(body)?body.replace(/<\/body>/i,`${VIDEO_JS}</body>`):body+VIDEO_JS;if(new URL(req.url).pathname.startsWith('/admin')&&!body.includes('/admin-video-sources-v14.17.js'))body=/<\/body>/i.test(body)?body.replace(/<\/body>/i,`${ADMIN_JS}</body>`):body+ADMIN_JS;const headers=new Headers(res.headers);headers.delete('content-length');headers.set('x-ainfo-version',VERSION);headers.set('x-ainfo-video-engine','multi-source');return new Response(body,{status:res.status,statusText:res.statusText,headers})}

async function route(req,env,ctx){const u=new URL(req.url),p=u.pathname;
if(p==='/api/videos/feed'&&req.method==='GET')return feed(req,env);
const vm=p.match(/^\/api\/videos\/(\d+)$/);if(vm&&req.method==='GET')return oneVideo(vm[1],env);
if(p==='/api/admin/video-sources'&&(req.method==='GET'||req.method==='POST')){const r=await adminSources(req,env,ctx);if(req.method==='POST'&&r.ok){try{const rows=await env.DB.prepare("SELECT * FROM video_sources WHERE provider='youtube' AND enabled=1 ORDER BY id DESC LIMIT 1").all();for(const s of rows.results||[])ctx?.waitUntil?.(subscribeYouTube(env,s))}catch{}}return r}
const sm=p.match(/^\/api\/admin\/video-sources\/(\d+)$/);if(sm&&req.method==='DELETE')return deleteSource(req,env,ctx,sm[1]);
if(p==='/api/admin/video-sources/sync'&&req.method==='POST')return adminSync(req,env,ctx);
if(p==='/api/admin/video-catalog'&&req.method==='GET')return adminCatalog(req,env,ctx);
if(p==='/api/admin/video-catalog/status'&&req.method==='POST')return setVideoStatus(req,env,ctx);
if(p==='/api/admin/video-sources/tiktok/connect'&&req.method==='GET')return tiktokConnect(req,env,ctx);
if(p==='/api/video/tiktok/callback'&&req.method==='GET')return tiktokCallback(req,env);
if(p==='/api/video/websub/youtube')return websub(req,env,ctx);
return inject(req,await previousWorker.fetch(req,env,ctx))}

export default{async fetch(req,env,ctx){try{return await route(req,env,ctx)}catch(e){console.error('AINFO V14.17 video engine',e);return previousWorker.fetch(req,env,ctx)}},async scheduled(event,env,ctx){if(typeof previousWorker.scheduled==='function')await previousWorker.scheduled(event,env,ctx);ctx?.waitUntil?.(syncAll(env))}};
